name: Build
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]

    env:
      GH_ACTIONS: true
      RUST_BACKTRACE: full
      DENO_BUILD_MODE: release

    steps:
      - name: Add msvc to PATH
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Create mpv.lib [windows]
        if: matrix.os == 'windows-latest'
        run: |
          cd win32-x64
          lib /def:mpv.def /name:mpv-1.dll /out:mpv.lib /MACHINE:X64
          7z a -tzip ../../win32-x64.zip mpv.lib
          cd ..\win32
          lib /def:mpv.def /name:mpv-1.dll /out:mpv.lib /MACHINE:X86
          7z a -tzip ../../win32.zip mpv.lib

      - name: Fix linking [mac]
        if: matrix.os == 'macOS-latest'
        run: |
          cd mac/lib
          find *.dylib | while read LINE
          do
              otool -l "$LINE" | grep "name " | grep "/usr/local/Cellar" | cut -d " " -f11 | while read LIB
              do
                  echo "$LINE -> $LIB"
                  install_name_tool -change "$LIB" "@executable_path/../Frameworks/$(basename $LIB)" $LINE
              done
          done

          cd ..
          zip ../mac.zip *

      - name: Release Plugin
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "libmpv release"
          draft: true
          files: |
            win32-x64.zip
            win32.zip
            mac.zip
